data = [{
    "id": "p3581519",
    "name": "Emporio Armani阿玛尼EA男士2020新款休闲鞋系带运动鞋单鞋男鞋",
    "activityId": 0,
    "productTitle": "Emporio Armani阿玛尼EA男士2020新款休闲鞋系带运动鞋单鞋男鞋",
    "deliveryType": 4,
    "deliveryName": "卖家保税",
    "stock": 40,
    "pic": "http://pic1.ymatou.com/G03/shangou/M09/6E/DE/CgzUIV8VPmSAZKZPAARqJJxlFF4789_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 999,
    "priceType": 0,
    "sellerId": 27355570,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613674907000,
    "validEnd": 1614279707000,
    "maxPrice": 999,
    "minPrice": 999,
    "marketPrice": 0,
    "version": "16.002",
    "isPspProduct": false,
    "countryId": 0,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 27355570,
        "avatarUrl": "http://img.ymatou.com/portal/images/default.png",
        "name": "Gohi海外专营店",
        "sellerLevel": "Semi-Pro",
        "level": 3,
        "countryName": "美国",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/America.png",
        "continent": "北美洲",
        "countryId": 0,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.8",
                "type": 1
            }
        }
    }
}, {
    "id": "78d1efa2-d377-4b7e-8477-55bbeef600d4",
    "name": "【2瓶】澳洲bio island 婴幼儿童鳕鱼肝油鱼油软胶囊90粒",
    "activityId": 8725,
    "productTitle": "【2瓶】澳洲bio island 婴幼儿童鳕鱼肝油鱼油软胶囊90粒",
    "deliveryType": 10,
    "stock": 50,
    "pic": "http://pic1.ymatou.com/G02/shangou/M02/1B/5E/CgzUClxK60OAN16XAACtILFsq2Y116_1_1_n_w_lb.jpg",
    "productType": 3,//产品
    "price": 233,
    "priceType": 3,//价格
    "sellerId": 20242919,
    "isFreeShipping": 0,
    "tariffType": 3,//运输
    "validStart": 1613088000000,
    "validEnd": 1614474000000,
    "maxPrice": 233,
    "minPrice": 233,
    "marketPrice": 350,
    "version": "4.001",
    "isPspProduct": false,
    "countryId": 4,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 20242919,
        "avatarUrl": "http://pic1.ymatou.com/G03/M09/E9/7C/CgzUIV-wr3uALlWTAADQTWZvgPI062_1_1_m.jpg",
        "name": "澳新健康生活馆",
        "sellerLevel": "Top",
        "level": 1,
        "countryName": "新西兰",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/NewZealand.png",
        "continent": "大洋洲",
        "countryId": 4,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.6",//综合
                "type": 1
            }
        }
    }
}, {
    "id": "1779324f-501f-457b-9324-ad61a8e9d479",
    "name": "【韩国直邮】爱茉莉染发剂美妆仙 泡沫染发剂 植物2N3N4N5N6N",
    "activityId": 8725,
    "productTitle": "【韩国直邮】爱茉莉染发剂美妆仙 泡沫染发剂 植物2N3N4N5N6N",
    "deliveryType": 10,
    "stock": 98,
    "pic": "http://pic1.ymatou.com/G02/shangou/M08/D6/EB/CgvUA1pewJyAPMfsAAM2Dj4bQrQ150_1_1_n_w_lb.jpg",
    "productType": 3,
    "price": 56,
    "priceType": 3,
    "sellerId": 14185968,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613088000000,
    "validEnd": 1614474000000,
    "maxPrice": 56,
    "minPrice": 56,
    "marketPrice": 99,
    "version": "12.007",
    "isPspProduct": false,
    "countryId": 2,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 14185968,
        "avatarUrl": "http://pic1.ymatou.com/G02/M0A/60/7E/CgvUA1iBtQOAWAWRAABgHdU2--U243_1_1_m.jpg",
        "name": "思美韩妆",
        "sellerLevel": "Top",
        "level": 1,
        "countryName": "韩国",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Korea.png",
        "continent": "亚洲",
        "countryId": 2,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.9",
                "type": 1
            }
        }
    }
}, {
    "id": "e0b8dae8-1eae-4073-bfd4-dbff6561230c",
    "name": "杯具熊杯子双层带盖茶水男女士便携玻璃杯防漏耐摔塑料杯",
    "activityId": 0,
    "productTitle": "杯具熊杯子双层带盖茶水男女士便携玻璃杯防漏耐摔塑料杯",
    "deliveryType": 10,
    "stock": 102,
    "pic": "http://pic1.ymatou.com/G02/shangou/M00/16/6F/CgvUBVm3Z3WAOBErAACkoyyw_lM318_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 68,
    "priceType": 0,
    "sellerId": 5806593,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613761471000,
    "validEnd": 1614366271000,
    "maxPrice": 68,
    "minPrice": 68,
    "marketPrice": 0,
    "version": "7.001",
    "isPspProduct": false,
    "countryId": 2,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 5806593,
        "avatarUrl": "http://pic1.ymatou.com/G02/M04/F3/49/CgzUC1x_VamAYKu2AAC835YWY7I010_1_1_m.jpg",
        "name": "柚子在首尔",
        "sellerLevel": "Pro",
        "level": 2,
        "countryName": "韩国",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Korea.png",
        "continent": "亚洲",
        "countryId": 2,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.8",
                "type": 1
            }
        }
    }
}, {
    "id": "699085cb-2aa3-4d9a-907b-05938a51696a",
    "name": "美国进口OXO海绵百洁布双层清洁喷刷 厨房锅刷可填充清洁剂不伤手",
    "activityId": 0,
    "productTitle": "美国进口OXO海绵百洁布双层清洁喷刷 厨房锅刷可填充清洁剂不伤手",
    "deliveryType": 10,
    "stock": 791,
    "pic": "http://pic1.ymatou.com/G02/shangou/M05/32/07/CgvUBFoBHWWAOpTWAAHibJyfDpI747_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 99,
    "priceType": 0,
    "sellerId": 2220242,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613894119000,
    "validEnd": 1614498919000,
    "maxPrice": 199,
    "minPrice": 99,
    "marketPrice": 0,
    "version": "5.001",
    "isPspProduct": false,
    "countryId": 5,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 2220242,
        "avatarUrl": "http://pic1.ymatou.com/G02/M00/AB/DF/CgvUBVpWtDWAZkzAAABw4UxkxyQ467_1_1_m.jpg",
        "name": "CC欧洲海外妙儿康旗舰店",
        "sellerLevel": "Semi-Pro",
        "level": 3,
        "countryName": "英国",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/England.png",
        "continent": "欧洲",
        "countryId": 5,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.6",
                "type": 1
            }
        }
    }
}, {
    "id": "p1146819",
    "name": "【3条装】Tommy Hilfiger汤米男士内裤套装 纯色棉质透气平角内裤",
    "activityId": 8725,
    "productTitle": "【3条装】Tommy Hilfiger汤米男士内裤套装 纯色棉质透气平角内裤",
    "deliveryType": 10,
    "stock": 45,
    "pic": "http://pic1.ymatou.com/G02/shangou/M04/9B/D9/CgzUC1xtIjSABIQxAACVmBPwE5s203_1_1_n_w_lb.jpg",
    "productType": 3,
    "price": 199,
    "priceType": 3,
    "sellerId": 20031671,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613991186000,
    "validEnd": 1614474000000,
    "maxPrice": 199,
    "minPrice": 199,
    "marketPrice": 450,
    "version": "17.001",
    "isPspProduct": false,
    "countryId": 0,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 20031671,
        "avatarUrl": "http://pic1.ymatou.com/G03/M00/9A/D9/CgzUFl6T2AWAEXJUAABIlW0geHE484_1_1_m.jpg",
        "name": "美购海外国际",
        "sellerLevel": "Semi-Pro",
        "level": 3,
        "countryName": "美国",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/America.png",
        "continent": "北美洲",
        "countryId": 0,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.9",
                "type": 1
            }
        }
    }
}, {
    "id": "p9092159",
    "name": "VERSACE运动鞋运动鞋",
    "activityId": 0,
    "productTitle": "VERSACE运动鞋运动鞋",
    "deliveryType": 1,
    "deliveryName": "进口贸易",
    "stock": 30,
    "pic": "http://pic1.ymatou.com/G03/shangou/M03/DE/EA/CgzUH2AiEtSAfGsLAABdZeTNmNI965_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 9100,
    "priceType": 0,
    "sellerId": 36477388,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1614005707000,
    "validEnd": 1614610507000,
    "maxPrice": 9100,
    "minPrice": 9100,
    "marketPrice": 0,
    "version": "2.001",
    "isPspProduct": false,
    "countryId": 666,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 36477388,
        "avatarUrl": "http://pic1.ymatou.com/G03/M01/E8/5E/CgzUIF7Qu9iAQ1f-AAJkT6KgWkc551_1_1_m.jpg",
        "name": "Musion奢品买手店",
        "sellerLevel": "初级买手",
        "countryName": "进口贸易",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/importtrade.png",
        "continent": "亚洲",
        "countryId": 666,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "5.0",
                "type": 1
            }
        }
    }
}, {
    "id": "7ce90a88-4cd5-463c-a50c-d4b512406bd7",
    "name": "娇韵诗红魔晶六七代可选纤体精华 提拉紧致保湿身体乳大红瓶200ml",
    "activityId": 0,
    "productTitle": "娇韵诗红魔晶六七代可选纤体精华 提拉紧致保湿身体乳大红瓶200ml",
    "deliveryType": 10,
    "stock": 240,
    "pic": "http://pic1.ymatou.com/G02/shangou/M00/13/83/CgvUBVm2yT-ANK0IAAEnK2u6zdQ786_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 289,
    "priceType": 0,
    "sellerId": 18398982,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613831533000,
    "validEnd": 1614436333000,
    "maxPrice": 289,
    "minPrice": 289,
    "marketPrice": 0,
    "version": "5.001",
    "isPspProduct": false,
    "countryId": 5,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 18398982,
        "avatarUrl": "http://pic1.ymatou.com/G02/M02/22/41/CgvUBFlH8K-AWs9dAAEmSh3ToFk441_1_1_m.jpg",
        "name": "英伦贵族买遍伦敦",
        "sellerLevel": "Pro",
        "level": 2,
        "countryName": "英国",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/England.png",
        "continent": "欧洲",
        "countryId": 5,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.6",
                "type": 1
            }
        }
    }
}, {
    "id": "4f1ad474-05c2-4db5-8378-c44cc8fa37e5",
    "name": "2瓶-澳洲Swisse钙片VD成人孕妇老人补钙 柠檬酸钙/娘娘钙/钙片",
    "activityId": 0,
    "productTitle": "2瓶-澳洲Swisse钙片VD成人孕妇老人补钙 柠檬酸钙/娘娘钙/钙片",
    "deliveryType": 4,
    "deliveryName": "卖家保税",
    "stock": 5922,
    "pic": "http://pic1.ymatou.com/G03/shangou/M01/61/34/CgzUIF8-C-iAIA52AALuC-Vkrhw731_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 69,
    "priceType": 0,
    "sellerId": 18394262,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613817230000,
    "validEnd": 1614422030000,
    "maxPrice": 179,
    "minPrice": 69,
    "marketPrice": 0,
    "version": "35.001",
    "isPspProduct": false,
    "countryId": 3,
    "isPreSale": true,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 18394262,
        "avatarUrl": "http://pic1.ymatou.com/G02/M05/FE/1F/CgvUA1iirH6AN2d8AACfrNgiIpw846_1_1_m.jpg",
        "name": "麦扣澳洲",
        "sellerLevel": "Semi-Pro",
        "level": 3,
        "countryName": "澳大利亚",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Australia.png",
        "continent": "大洋洲",
        "countryId": 3,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.7",
                "type": 1
            }
        }
    }
}, {
    "id": "p1419669",
    "name": "【國內现货】日本VAPE驱蚊液驱蚊喷雾宝宝防蚊液儿童防蚊喷雾儿童",
    "activityId": 0,
    "productTitle": "【國內现货】日本VAPE驱蚊液驱蚊喷雾宝宝防蚊液儿童防蚊喷雾儿童",
    "deliveryType": 10,
    "stock": 1878,
    "pic": "http://pic1.ymatou.com/G02/shangou/M08/5D/59/CgzUClzB5EaANZjnAAHHtMRUhT8716_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 47,
    "priceType": 0,
    "sellerId": 24297131,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613941158000,
    "validEnd": 1614545958000,
    "maxPrice": 47,
    "minPrice": 47,
    "marketPrice": 0,
    "version": "5.001",
    "isPspProduct": false,
    "countryId": 1,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 24297131,
        "avatarUrl": "http://pic1.ymatou.com/G02/M0A/57/FB/CgzUC15g_OqAb0fyAAC2MF4fhGg730_1_1_m.jpg",
        "name": "日本三越本店",
        "sellerLevel": "Semi-Pro",
        "level": 3,
        "countryName": "日本",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Japan.png",
        "continent": "亚洲",
        "countryId": 1,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.6",
                "type": 1
            }
        }
    }
}, {
    "id": "p7795625",
    "name": "【礼盒装】Calvin Klein/CK皮带男士双面双扣平滑针扣腰带75613",
    "activityId": 8725,
    "productTitle": "【礼盒装】Calvin Klein/CK皮带男士双面双扣平滑针扣腰带75613",
    "deliveryType": 10,
    "stock": 100,
    "pic": "http://pic1.ymatou.com/G03/shangou/M07/87/46/CgzUH1_XFAKAG3IQAAHMbZOmSm8715_1_1_n_w_lb.jpg",
    "productType": 3,
    "price": 299,
    "priceType": 3,
    "sellerId": 20031671,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1614000898000,
    "validEnd": 1614474000000,
    "maxPrice": 299,
    "minPrice": 299,
    "marketPrice": 599,
    "version": "2.01",
    "isPspProduct": false,
    "countryId": 0,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 20031671,
        "avatarUrl": "http://pic1.ymatou.com/G03/M00/9A/D9/CgzUFl6T2AWAEXJUAABIlW0geHE484_1_1_m.jpg",
        "name": "美购海外国际",
        "sellerLevel": "Semi-Pro",
        "level": 3,
        "countryName": "美国",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/America.png",
        "continent": "北美洲",
        "countryId": 0,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.9",
                "type": 1
            }
        }
    }
}, {
    "id": "425507a5-6520-4ef4-94c3-21fd57ca717b",
    "name": "澳洲Aptamil可瑞康爱他美金装宝宝儿童奶粉900g 1段/2段/3段/4段",
    "activityId": 0,
    "productTitle": "澳洲Aptamil可瑞康爱他美金装宝宝儿童奶粉900g 1段/2段/3段/4段",
    "deliveryType": 4,
    "deliveryName": "卖家保税",
    "stock": 30193,
    "pic": "http://pic1.ymatou.com/G03/shangou/M06/9A/7B/CgzUH19pkguAWAiwAAMkclyy6Sg278_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 445,
    "priceType": 0,
    "sellerId": 18394262,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613817230000,
    "validEnd": 1614422030000,
    "maxPrice": 499,
    "minPrice": 445,
    "marketPrice": 0,
    "version": "13.031",
    "isPspProduct": false,
    "countryId": 3,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 18394262,
        "avatarUrl": "http://pic1.ymatou.com/G02/M05/FE/1F/CgvUA1iirH6AN2d8AACfrNgiIpw846_1_1_m.jpg",
        "name": "麦扣澳洲",
        "sellerLevel": "Semi-Pro",
        "level": 3,
        "countryName": "澳大利亚",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Australia.png",
        "continent": "大洋洲",
        "countryId": 3,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.7",
                "type": 1
            }
        }
    }
}, {
    "id": "p9132379",
    "name": "lv新款男鞋 运动鞋 休闲鞋 ",
    "activityId": 0,
    "productTitle": "lv新款男鞋 运动鞋 休闲鞋 ",
    "deliveryType": 10,
    "stock": 13,
    "pic": "http://pic1.ymatou.com/G03/shangou/M03/EA/E3/CgzUIGAmo_OAYezxAARwFEa023M940_500_667_n_w_lb.jpg",
    "productType": 2,
    "price": 7100,
    "priceType": 0,
    "sellerId": 40580844,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613931617000,
    "validEnd": 1614536417000,
    "maxPrice": 7100,
    "minPrice": 7100,
    "marketPrice": 0,
    "version": "1.001",
    "isPspProduct": false,
    "countryId": 6,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 40580844,
        "avatarUrl": "http://pic1.ymatou.com/G03/M04/E8/56/CgzUIF_8FVGAedDtAACJJ0toIrw837_1_1_m.jpg",
        "name": "米尚易购",
        "sellerLevel": "Semi-Pro",
        "level": 3,
        "countryName": "意大利",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Italy.png",
        "continent": "欧洲",
        "countryId": 6,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.9",
                "type": 1
            }
        }
    }
}, {
    "id": "3fb4a316-495c-4245-a5e1-c26a15640e17",
    "name": "Train女の欲望黑色加厚款发热瘦腿袜丝袜打底裤",
    "activityId": 0,
    "productTitle": "Train女の欲望黑色加厚款发热瘦腿袜丝袜打底裤",
    "deliveryType": 10,
    "stock": 22,
    "pic": "http://pic1.ymatou.com/G02/shangou/M02/7F/82/CgvUA1nsOAyAaxcpAAQvmWMzDJA010_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 75,
    "priceType": 0,
    "sellerId": 520462,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613921452000,
    "validEnd": 1614526252000,
    "maxPrice": 85,
    "minPrice": 75,
    "marketPrice": 0,
    "version": "18.002",
    "isPspProduct": false,
    "countryId": 1,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 520462,
        "avatarUrl": "http://pic1.ymatou.com/G03/M00/C9/3D/CgzUFl58c_mAY3npAAJWANJQdeQ686_1_1_m.jpg",
        "name": "东京的苹果",
        "sellerLevel": "初级买手",
        "countryName": "日本",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Japan.png",
        "continent": "亚洲",
        "countryId": 1,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.7",
                "type": 1
            }
        }
    }
}, {
    "id": "p9137731",
    "name": "Fendi 芬迪老花 大logo 围巾 火爆的一塌糊涂",
    "activityId": 0,
    "productTitle": "Fendi 芬迪老花 大logo 围巾 火爆的一塌糊涂",
    "deliveryType": 10,
    "stock": 5,
    "stockDesc": "仅剩5件",
    "pic": "http://pic1.ymatou.com/G03/shangou/M05/A3/1A/CgzUIGAc1cuAJT0gAAFWsir98P4027_200_267_n_w_lb.jpg",
    "productType": 2,
    "price": 5799,
    "priceType": 0,
    "sellerId": 15564674,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1614008982000,
    "validEnd": 1614613782000,
    "maxPrice": 5799,
    "minPrice": 5799,
    "marketPrice": 0,
    "version": "1.001",
    "isPspProduct": false,
    "countryId": 6,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 15564674,
        "avatarUrl": "http://pic1.ymatou.com/G02/M06/0E/5E/CgvUBVoZevSAKnbiAABnolOp8b8565_1_1_m.jpg",
        "name": "KANGITALY",
        "sellerLevel": "Semi-Pro",
        "level": 3,
        "countryName": "意大利",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Italy.png",
        "continent": "欧洲",
        "countryId": 6,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.7",
                "type": 1
            }
        }
    }
}, {
    "id": "16e8249f-98d3-4efd-91a5-9e6fb6738331",
    "name": "新包装 澳洲Bio Island婴幼儿童DHA海藻油60粒 促进脑发育",
    "activityId": 8725,
    "productTitle": "新包装 澳洲Bio Island婴幼儿童DHA海藻油60粒 促进脑发育",
    "deliveryType": 4,
    "deliveryName": "卖家保税",
    "stock": 147,
    "pic": "http://pic1.ymatou.com/G03/shangou/M06/57/E3/CgzUF15vJ0yAL5gYAAMogoCtbxg550_1_1_n_w_lb.jpg",
    "productType": 3,
    "price": 104,
    "priceType": 3,
    "sellerId": 15063972,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613088000000,
    "validEnd": 1614474000000,
    "maxPrice": 237,
    "minPrice": 104,
    "marketPrice": 299,
    "version": "24.075",
    "isPspProduct": false,
    "countryId": 3,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 15063972,
        "avatarUrl": "http://pic1.ymatou.com/G02/M06/BB/20/CgvUA1c6qTGAJD3kAABDbjhdr54824_m.jpg",
        "name": "至臻澳洲",
        "sellerLevel": "Pro",
        "level": 2,
        "countryName": "澳大利亚",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Australia.png",
        "continent": "大洋洲",
        "countryId": 3,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.7",
                "type": 1
            }
        }
    }
}, {
    "id": "55b9a8bd-9b82-480b-8e64-daaf2ecdc0bb",
    "name": "Salvatore Ferragamo 菲拉格慕 男士黑色牛皮腰带 板扣式腰带皮带",
    "activityId": 8729,
    "productTitle": "Salvatore Ferragamo 菲拉格慕 男士黑色牛皮腰带 板扣式腰带皮带",
    "deliveryType": 10,
    "stock": 126,
    "pic": "http://pic1.ymatou.com/G03/shangou/M03/CF/F6/CgzUIF7PLzmAWBy-AAlZ079RKnQ531_1_1_n_w_lb.jpg",
    "productType": 3,
    "price": 2299,
    "priceType": 3,
    "sellerId": 5257358,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613751797000,
    "validEnd": 1614474000000,
    "maxPrice": 2299,
    "minPrice": 2299,
    "marketPrice": 3600,
    "version": "51.001",
    "isPspProduct": false,
    "countryId": 6,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 5257358,
        "avatarUrl": "http://pic1.ymatou.com/G02/M03/F4/59/CgvUBVhAsbWAN6wVAACQJcbzuXQ045_1_1_m.jpg",
        "name": "港龙欧尚",
        "sellerLevel": "Pro",
        "level": 2,
        "countryName": "意大利",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Italy.png",
        "continent": "欧洲",
        "countryId": 6,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.8",
                "type": 1
            }
        }
    }
}, {
    "id": "p5311638",
    "name": "20新品 EMPORIO ARMANI  阿玛尼 男士平角内裤 四角裤 111210",
    "activityId": 0,
    "productTitle": "20新品 EMPORIO ARMANI  阿玛尼 男士平角内裤 四角裤 111210",
    "deliveryType": 10,
    "stock": 3,
    "stockDesc": "仅剩3件",
    "pic": "http://pic1.ymatou.com/G03/shangou/M01/75/8E/CgzUH17_Tj2AN-yvAADLLkGHmAI298_100_101_n_w_lb.jpg",
    "productType": 2,
    "price": 335,
    "priceType": 0,
    "sellerId": 23100214,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613857069000,
    "validEnd": 1614461869000,
    "maxPrice": 335,
    "minPrice": 335,
    "marketPrice": 0,
    "version": "3.004",
    "isPspProduct": false,
    "countryId": 47,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 23100214,
        "avatarUrl": "http://pic1.ymatou.com/G03/M08/D1/2C/CgzUIF9HqN2AJ6hBAAGLcrSc0k4865_1_1_m.jpg",
        "name": "CFASHION",
        "sellerLevel": "初级买手",
        "countryName": "香港",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Hongkong.png",
        "continent": "亚洲",
        "countryId": 47,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.8",
                "type": 1
            }
        }
    }
}, {
    "id": "b2fd9159-5409-4498-9ee1-6fe63dd96ece",
    "name": "美国GNC健安喜减肥瘦身减脂燃脂护肝片左旋肉碱片男士备孕60粒",
    "activityId": 8725,
    "productTitle": "美国GNC健安喜减肥瘦身减脂燃脂护肝片左旋肉碱片男士备孕60粒",
    "deliveryType": 10,
    "stock": 48,
    "pic": "http://pic1.ymatou.com/G03/shangou/M03/7B/A7/CgzUH18WhwCANjScAAJAg2ltlvo465_1_1_n_w_lb.JPG",
    "productType": 3,
    "price": 239,
    "priceType": 3,
    "sellerId": 11988090,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613088000000,
    "validEnd": 1614474000000,
    "maxPrice": 239,
    "minPrice": 239,
    "marketPrice": 297,
    "version": "6.002",
    "isPspProduct": false,
    "countryId": 0,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 11988090,
        "avatarUrl": "http://pic1.ymatou.com/G02/M00/6B/58/CgvUA1gs2q-AVzQHAAA8asi0sUA163_1_1_m.jpg",
        "name": "Ivy恬色",
        "sellerLevel": "初级买手",
        "countryName": "美国",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/America.png",
        "continent": "北美洲",
        "countryId": 0,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.6",
                "type": 1
            }
        }
    }
}, {
    "id": "p7814759",
    "name": "3条装 CK男士舒适莫代尔中腰内裤平角礼盒三条装黑白灰",
    "activityId": 0,
    "productTitle": "3条装 CK男士舒适莫代尔中腰内裤平角礼盒三条装黑白灰",
    "deliveryType": 10,
    "stock": 3625,
    "pic": "http://pic1.ymatou.com/G03/shangou/M06/77/93/CgzUIF_V0KaAb8Y_AAIOiPRCvWI338_1_1_n_w_lb.jpg",
    "productType": 2,
    "price": 199,
    "priceType": 0,
    "sellerId": 29783122,
    "isFreeShipping": 0,
    "tariffType": 3,
    "validStart": 1613834522000,
    "validEnd": 1614439322000,
    "maxPrice": 199,
    "minPrice": 199,
    "marketPrice": 0,
    "version": "1.003",
    "isPspProduct": false,
    "countryId": 51,
    "isPreSale": false,
    "state": 0,
    "pspAbtest": true,
    "sellerInfo": {
        "id": 29783122,
        "avatarUrl": "http://pic1.ymatou.com/G02/M09/4C/49/CgzUC15gxLiAVGZKAAFHr1sjlfI442_1_1_m.jpg",
        "name": "THAILAND皇权",
        "sellerLevel": "Pro",
        "level": 2,
        "countryName": "泰国",
        "countryIconUrl": "http://img.ymatou.com/app/flag/circle/Thailand.png",
        "continent": "亚洲",
        "countryId": 51,
        "flagship": 0,
        "brandLogo": null,
        "certification": 1,
        "sellerDSR": {
            "DSRPoint": {
                "point": "4.8",
                "type": 1
            }
        }
    }
}]